build1:
  stage: build
  script:
    - cd /home/centos/
    - git clone https://github.com/OlehKuryshko/eSchool.git
    - cd /home/centos/eSchool/
    - mvn clean package -DskipTests
    - mv /home/centos/eSchool/target/eschool.jar /home/centos/eschool.jar
    - chmod 0777 /home/centos/eschool.jar
    - rm -rf /home/centos/eSchool/
    - rm -rf /home/centos/builds/
  tags:
    - my-runner

test1:
  stage: test
  script:
    - mvn test -Dmaven.test.failure.ignore=true
    - rm -rf /home/centos/builds/
  tags:
    - my-runner

deploy1:
  stage: deploy
  script:
    - ansible-playbook -i /home/centos/ansible/hosts.txt /home/centos/ansible/playbook_ci_be.yml
    - rm -rf /home/centos/eschool.jar
    - rm -rf /home/centos/builds/
  when: manual
  tags:
    - my-runner
#final_test_0